shared:
  risk:
    session_start: '09:15'
    session_end: '15:20'
    max_day_loss_pct: 2.0
    losers_per_day: 6
    cooldown_minutes: 5
  sizing:
    risk_per_trade_pct: 0.6
    max_stock_leverage: 2.0
    default_stop_pct: 1.0
  rate_limiter:
    qps: 6
    burst: 10
    base_delay: 0.5
    max_delay: 4.0
    min_spacing: 0.25
stocks:
  cash_balance: 750000
  poll_interval: 20
  idempotency_ttl: 120
  watchlist:
    - symbol: RELIANCE
      allow_shorts: false
      atr_multiple: 1.2
      stop_loss_pct: 1.0
      target_pct: 2.0
      rr_multiple: 2.5
      max_spread_pct: 0.6
      estimated_spread_pct: 0.25
      lot_size: 1
      trailing_sl_points: 4.0
      trailing_jump: 2.0
    - symbol: TCS
      allow_shorts: true
      atr_multiple: 1.1
      stop_loss_pct: 1.0
      target_pct: 2.0
      rr_multiple: 2.0
      max_spread_pct: 0.5
      estimated_spread_pct: 0.18
      lot_size: 1
